namespace SpriteKind {
    export const helper = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Projectile, assets.tile`myTile3`, function (sprite, location) {
	
})
scene.onOverlapTile(SpriteKind.Projectile, assets.tile`myTile9`, function (sprite, location) {
	
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (controller.left.isPressed()) {
        projectile = sprites.createProjectileFromSprite(img`
            e e e e e e 
            e e e e e e 
            e d d d d d 
            d d 8 d 8 d 
            d d d d d d 
            d d 3 3 3 d 
            `, STEPHE, -71, 2)
    } else if (controller.right.isPressed()) {
        projectile = sprites.createProjectileFromSprite(img`
            e e e e e e 
            e e e e e e 
            e d d d d d 
            d d 8 d 8 d 
            d d d d d d 
            d d 3 3 3 d 
            `, STEPHE, 71, 2)
    } else if (controller.up.isPressed()) {
        projectile = sprites.createProjectileFromSprite(img`
            e e e e e e 
            e e e e e e 
            e d d d d d 
            d d 8 d 8 d 
            d d d d d d 
            d d 3 3 3 d 
            `, STEPHE, 1, -77)
    } else {
        music.pewPew.play()
        projectile = sprites.createProjectileFromSprite(img`
            e e e e e e 
            e e e e e e 
            e d d d d d 
            d d 8 d 8 d 
            d d d d d d 
            d d 3 3 3 d 
            `, STEPHE, 3, 79)
        projectile.setBounceOnWall(false)
    }
})
scene.onOverlapTile(SpriteKind.Projectile, assets.tile`myTile28`, function (sprite, location) {
    music.knock.play()
    tiles.setTileAt(location, assets.tile`myTile29`)
    tiles.setWallAt(location, false)
})
scene.onOverlapTile(SpriteKind.Projectile, assets.tile`myTile`, function (sprite, location) {
	
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Water) {
        STEPHE.vy = -50
    } else {
        if (STEPHE.isHittingTile(CollisionDirection.Bottom)) {
            STEPHE.vy = -170
        }
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    STEPHE,
    [img`
        .......eeeeeeeeeeeeeeee.....
        .......eeeeeeeeeeeeeeee.....
        .......eeeeeeeeeeeeeeee.....
        .......eeeeeeeeeeeeeeee.....
        .......edddddddddddeeee.....
        .......dddddddddddddeee.....
        .......dddddddddddddbbe.....
        .......dd881ddd188ddbde.....
        .......dd881ddd188ddbde.....
        .......dddddbbbdddddbbe.....
        .......dddddbbbdddddbbe.....
        .......dddeedddeedddbbb.....
        .......dddeeeeeeedddbbb.....
        .......dddee33eeedddbbb.....
        ....8888666336666666666668..
        ....888d6666666666666ddddb8.
        ....dddd6666666666666ddddbb.
        ....bddd666666666666ddddbb..
        .....ddd666666666666ddddbb..
        .....bdd666666666666ddddbb..
        .....bdd66666666666ddddbb...
        ......bd66666666666ddddbb...
        ......bd6666666666ddddbb....
        .......d6688888888ffddbb....
        .......b688888888888f.......
        .......88888cc..88888cc.....
        .......88888cc...88888cc....
        ......88888cc....88888cc....
        .....888888cc.....88888cc...
        ....dd8888cc......88888ccb..
        .....ddd88cc.......668ddbb..
        ........dbb........bddd.....
        `,img`
        ......eeeeeeeeeeeeeeee......
        ......eeeeeeeeeeeeeeee......
        ......eeeeeeeeeeeeeeee......
        ......eeeeeeeeeeeeeeee......
        ......edddddddddddeeee......
        ......dddddddddddddeee......
        ......dddddddddddddbbe......
        ......dd881ddd188ddbde......
        ......dd881ddd188ddbde......
        ......dddddbbbdddddbbe......
        ......dddddbbbdddddbbe......
        ......dddeedddeedddbbb......
        ......dddeeeeeeedddbbb......
        ......dddee33eeedddbbb......
        ...88666666633666666666688..
        ...ddd666666666666666ddddd..
        ...ddd66666666666666bddddd..
        ..ddddd6666666666666bdddddd.
        ..ddddd6666666666666.bddddd.
        ..ddddb6666666666666.bddddd.
        .dddddb6666666666666.bddddd.
        .dddddb6666666666666..bdddd.
        .dddddb6666666666666..bdddd.
        ...dddb6668888888888..bbdd..
        .......6888888888888c.......
        .......88888ccf8888cc.......
        .......88888ccf8888cc......d
        ........8888cf8888cc.......d
        ........8888cf8888cc.......d
        .........88bf6888cc.........
        .........88bddd88cc.........
        .........dd....dbb..........
        `],
    200,
    true
    )
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, STEPHE)
    STEPHE.setImage(img`
        ......eeeeeeeeeeeeeeee.....
        ......eeeeeeeeeeeeeeee.....
        ......eeeeeeeeeeeeeeee.....
        ......eeeeeeeeeeeeeeee.....
        ......eeeeddddddddddde.....
        ......eeeddddddddddddd.....
        ......ebbddddddddddddd.....
        ......edbdd881ddd188dd.....
        ......edbdd881ddd188dd.....
        ......ebbdddddbbbddddd.....
        ......ebbdddddbbbddddd.....
        ......bbbdddeedddeeddd.....
        ......bbbdddeeeeeeeddd.....
        ......bbbdddeee33eeddd.....
        ..888666666666633666668888.
        ..bbddd6666666666666668888.
        ..bbdddd66666666666666bddd.
        ..bbdddd66666666666666bddd.
        ..bbdddd66666666666666bddd.
        ..bbdddd66666666666666bddd.
        ..bbdddd66666666666666bddd.
        ..bbdddd66666666666666bddd.
        ..bbdddd66666666666666bddd.
        ..bbdddd88888888888866bddd.
        ..bbdddd88888888888866bddd.
        .......cc88888.cc88888.....
        .......cc88888.cc88888.....
        .......cc88888.cc88888.....
        .......cc88888.cc88888.....
        .......cc88888.cc88888.....
        .......cc88888.cc88888.....
        .......bbddddd.bbddddd.....
        `)
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, STEPHE)
    STEPHE.setImage(assets.image`Assdv`)
})
function MakeWall () {
    Walls = [
    tiles.getTilesByType(assets.tile`myTile`),
    tiles.getTilesByType(assets.tile`myTile0`),
    tiles.getTilesByType(assets.tile`myTile1`),
    tiles.getTilesByType(assets.tile`myTile9`),
    tiles.getTilesByType(assets.tile`myTile16`),
    tiles.getTilesByType(assets.tile`myTile15`),
    tiles.getTilesByType(assets.tile`myTile10`),
    tiles.getTilesByType(assets.tile`myTile3`),
    tiles.getTilesByType(assets.tile`myTile44`),
    tiles.getTilesByType(assets.tile`myTile45`),
    tiles.getTilesByType(assets.tile`myTile28`),
    tiles.getTilesByType(assets.tile`myTile30`),
    tiles.getTilesByType(assets.tile`myTile31`),
    tiles.getTilesByType(assets.tile`myTile31`)
    ]
    for (let index = 0; index < Walls.length; index++) {
        for (let value of Walls[Number2]) {
            tiles.setWallAt(value, true)
        }
        Number2 += 1
    }
}
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    STEPHE,
    [img`
        .....eeeeeeeeeeeeeeee.......
        .....eeeeeeeeeeeeeeee.......
        .....eeeeeeeeeeeeeeee.......
        .....eeeeeeeeeeeeeeee.......
        .....eeeeddddddddddde.......
        .....eeeddddddddddddd.......
        .....ebbddddddddddddd.......
        .....edbdd881ddd188dd.......
        .....edbdd881ddd188dd.......
        .....ebbdddddbbbddddd.......
        .....ebbdddddbbbddddd.......
        .....bbbdddeedddeeddd.......
        .....bbbdddeeeeeeeddd.......
        .....bbbdddeee33eeddd.......
        ..8666666666666336668888....
        .8bdddd6666666666666d888....
        .bbdddd6666666666666dddd....
        ..bbdddd666666666666dddb....
        ..bbdddd666666666666ddd.....
        ..bbdddd666666666666ddb.....
        ...bbdddd66666666666ddb.....
        ...bbdddd66666666666db......
        ....bbdddd6666666666db......
        ....bbddff8888888866d.......
        .......f888888888886b.......
        .....cc88888..cc88888.......
        ....cc88888...cc88888.......
        ....cc88888....cc88888......
        ...cc88888.....cc888888.....
        ..bcc88888......cc8888dd....
        ..bbdd866.......cc88ddd.....
        .....dddb........bbd........
        `,img`
        ......eeeeeeeeeeeeeeee......
        ......eeeeeeeeeeeeeeee......
        ......eeeeeeeeeeeeeeee......
        ......eeeeeeeeeeeeeeee......
        ......eeeeddddddddddde......
        ......eeeddddddddddddd......
        ......ebbddddddddddddd......
        ......edbdd881ddd188dd......
        ......edbdd881ddd188dd......
        ......ebbdddddbbbddddd......
        ......ebbdddddbbbddddd......
        ......bbbdddeedddeeddd......
        ......bbbdddeeeeeeeddd......
        ......bbbdddeee33eeddd......
        ..88666666666633666666688...
        ..ddddd666666666666666ddd...
        ..dddddb66666666666666ddd...
        .ddddddb6666666666666ddddd..
        .dddddb.6666666666666ddddd..
        .dddddb.6666666666666bdddd..
        ddddddb.6666666666666bddddd.
        dddddb..6666666666666bddddd.
        dddddb..6666666666666bddddd.
        ..ddbb..8888888888666bddd...
        .......c8888888888886.......
        .......cc8888fcc88888.......
        .......cc8888fcc88888.......
        ........cc8888fc8888........
        ........cc8888fc8888........
        .........cc8886fb88.........
        .........cc88dddb88.........
        ..........bbd....dd.........
        `],
    200,
    true
    )
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile8`, function (sprite, location) {
    for (let index = 0; index < 5; index++) {
        pause(200)
        music.playMelody("B B B F F F F F ", 3000)
        info.changeLifeBy(-2)
    }
})
scene.onHitWall(SpriteKind.Projectile, function (sprite, location) {
    music.knock.play()
    tiles.setTileAt(location, assets.tile`myTile29`)
    tiles.setWallAt(location, false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`transparency16`, function (sprite, location) {
	
})
scene.onOverlapTile(SpriteKind.Projectile, assets.tile`transparency16`, function (sprite, location) {
	
})
let Number2 = 0
let Walls: tiles.Location[][] = []
let projectile: Sprite = null
let Water = false
let STEPHE: Sprite = null
let mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Enemy)
tiles.setCurrentTilemap(tilemap`level1`)
STEPHE = sprites.create(assets.image`Assdv`, SpriteKind.Player)
controller.moveSprite(STEPHE, 61, 0)
let village_people = sprites.create(img`
    ........................
    ........................
    ........................
    ........dddddddd........
    ........dddddddd........
    ........dddddddd........
    ........dddddddd........
    ........dddddddd........
    ........dddddddd........
    ........dffffffd........
    ........d17dd71d........
    ........dddeeddd........
    ........ddceecdd........
    ........dddeeddd........
    ....eeeecfdeedfceeee....
    ....eeeecefddfeceeee....
    ....eeeeceeffeeceeee....
    ....eeeecccccccceeee....
    ...eeeeeeeecbeeeeeeee...
    ...eeeeeeeecbeeeeeeee...
    ...eeeeeeeecbeeeeeeee...
    ...eeeeeeeecbeeeeeeee...
    ...cccccccccccccccccc...
    ....cccccccccccccccc....
    .......eeeeffeeee.......
    .......eeeecbeeee.......
    .......eeeecbeeee.......
    .......eeeecbeeee.......
    .......eeeecbeeee.......
    .......eeeecbeeee.......
    .......eeeecbeeee.......
    .......eeeecbeeee.......
    .......eeeecbeeee.......
    .......eeeecbeeee.......
    .......eeeecbeeee.......
    ........ffffffff........
    ........eeeeeeee........
    ........eeeeeeee........
    ........bbbbbbbb........
    ........bbbbbbbb........
    `, SpriteKind.helper)
tiles.placeOnTile(village_people, tiles.getTileLocation(41, 50))
scene.cameraFollowSprite(STEPHE)
info.setLife(10)
scene.setBackgroundColor(9)
MakeWall()
tiles.placeOnTile(STEPHE, tiles.getTileLocation(84, 0))
Water = STEPHE.tileKindAt(TileDirection.Center, assets.tile`myTile11`) || STEPHE.tileKindAt(TileDirection.Center, assets.tile`myTile12`) || (STEPHE.tileKindAt(TileDirection.Center, assets.tile`myTile13`) || STEPHE.tileKindAt(TileDirection.Center, assets.tile`myTile14`))
forever(function () {
    if (Water) {
        STEPHE.fy = 500
        STEPHE.ay = 2
    } else {
        STEPHE.ay = 420
    }
})
